
hardcode_state = {
    'hunger': {
      0: "Fully satiated, feeling energized and satisfied after a wholesome meal.",
      1: "Very slightly hungry, but still comfortable and content.",
      2: "Mildly hungry, could eat but not urgent.",
      3: "Noticeably hungry, starting to think about food.",
      4: "Moderately hungry, definitely ready to eat.",
      5: "Quite hungry, distraction from tasks begins.",
      6: "Very hungry, stomach might be growling.",
      7: "Extremely hungry, hard to focus on anything else.",
      8: "Very uncomfortable, feeling weak and irritable.",
      9: "Near starvation, light-headed and lacking energy.",
      10: "Completely starved, feeling weak and unable to concentrate due to a severe lack of food."
    },
    'thirst': {
      0: "Completely hydrated, feeling refreshed with your body functioning optimally.",
      1: "Very slightly thirsty, but still comfortable.",
      2: "Mildly thirsty, could drink but not urgent.",
      3: "Noticeably thirsty, starting to think about water.",
      4: "Moderately thirsty, would like a drink soon.",
      5: "Quite thirsty, mild discomfort setting in.",
      6: "Very thirsty, distraction from tasks begins.",
      7: "Extremely thirsty, dry mouth and difficulty concentrating.",
      8: "Uncomfortably thirsty, feeling parched and irritable.",
      9: "Severely dehydrated, experiencing dizziness and fatigue.",
      10: "Extremely dehydrated, with a dry mouth and feelings of dizziness and exhaustion."
    },
    'comfort':{
      0: "Extreme discomfort, experiencing pain or severe physical unease.",
      1: "Very uncomfortable, significant physical distress.",
      2: "Uncomfortable, noticeable unease.",
      3: "Mild discomfort, aware of some physical tension.",
      4: "Slightly uncomfortable, minor irritations present.",
      5: "Neutral, neither comfortable nor uncomfortable.",
      6: "Somewhat comfortable, generally at ease.",
      7: "Comfortable, feeling relaxed and content.",
      8: "Very comfortable, enjoying the surroundings.",
      9: "Extremely comfortable, feeling cozy and content.",
      10: "Perfect comfort, feeling cozy and relaxed in your environment."
    },
    'health': {
      0: "Critical condition, experiencing severe illness or injury.",
      1: "Very poor health, significant medical issues present.",
      2: "Poor health, struggling with serious symptoms.",
      3: "Below average health, dealing with noticeable health problems.",
      4: "Somewhat unhealthy, experiencing minor ailments.",
      5: "Average health, occasional discomfort or minor issues.",
      6: "Fairly healthy, generally well with minor concerns.",
      7: "Good health, feeling well with no major issues.",
      8: "Very good health, feeling strong and energetic.",
      9: "Excellent health, vibrant and full of energy.",
      10: "Perfect health, feeling strong, energetic, and free from ailments."
    },
    'sleepiness': {
      0: "Fully rested, feeling alert and ready to tackle the day.",
      1: "Very slightly sleepy, but still focused and awake.",
      2: "Mildly sleepy, could nap but not necessary.",
      3: "Noticeably sleepy, starting to think about resting.",
      4: "Somewhat sleepy, mild desire to sleep.",
      5: "Moderately sleepy, distraction from tasks begins.",
      6: "Quite sleepy, feeling the need to rest soon.",
      7: "Very sleepy, struggling to maintain focus.",
      8: "Extremely sleepy, eyes heavy and concentration difficult.",
      9: "Severely sleepy, barely able to stay awake.",
      10: "Utterly exhausted, struggling to keep eyes open and concentrate."
    },
    'joyfulness': {
      0: "Completely miserable, experiencing profound sadness and a lack of pleasure.",
      1: "Very unhappy, feeling significant sadness.",
      2: "Unhappy, struggling to find joy in activities.",
      3: "Somewhat unhappy, occasional moments of sadness.",
      4: "Slightly down, but able to find small joys.",
      5: "Neutral, neither happy nor sad.",
      6: "Mildly happy, feeling some contentment.",
      7: "Quite happy, experiencing regular moments of joy.",
      8: "Very happy, consistently feeling positive and content.",
      9: "Extremely happy, feeling joyful and satisfied.",
      10: "Immense joy, feeling incredibly happy and content."
    },
    'cleanliness': {
      0: "Utterly filthy, with a strong need to wash and clean yourself immediately.",
      1: "Very dirty, feeling uncomfortably unclean.",
      2: "Dirty, aware of grime and discomfort.",
      3: "Somewhat unclean, noticing areas needing attention.",
      4: "Slightly unclean, minor discomfort.",
      5: "Neutral, neither clean nor dirty.",
      6: "Somewhat clean, generally fresh but could improve.",
      7: "Clean, feeling refreshed and comfortable.",
      8: "Very clean, feeling fresh and hygienic.",
      9: "Extremely clean, almost spotless.",
      10: "Impeccably clean, fresh, and hygienic from head to toe."
    },
    'safety': {
      0: "In extreme danger, feeling vulnerable and constantly threatened.",
      1: "Very unsafe, high risk of harm.",
      2: "Unsafe, feeling exposed to potential danger.",
      3: "Somewhat unsafe, aware of possible threats.",
      4: "Slightly unsafe, minor concerns about safety.",
      5: "Neutral, neither safe nor unsafe.",
      6: "Somewhat safe, generally secure but cautious.",
      7: "Safe, feeling secure in the environment.",
      8: "Very safe, minimal concerns about danger.",
      9: "Extremely safe, feeling well-protected.",
      10: "Completely safe, secure, and protected in your current environment."
    },
    'passion': {
      0: "Extremely lazy, completely unmotivated to work or be productive.",
      1: "Very unmotivated, struggling to find any drive.",
      2: "Unmotivated, minimal interest in tasks.",
      3: "Somewhat lazy, occasional bursts of effort.",
      4: "Slightly unmotivated, reluctant to start tasks.",
      5: "Neutral, neither motivated nor unmotivated.",
      6: "Somewhat motivated, occasional enthusiasm.",
      7: "Motivated, generally eager to engage in tasks.",
      8: "Very motivated, consistently putting in effort.",
      9: "Highly motivated, driven and focused on goals.",
      10: "Highly diligent, feeling motivated and putting in great effort in your tasks."
    },
    'spiritual satisfaction': {
      0: "Spiritually empty, lacking any sense of purpose or inner peace.",
      1: "Experiencing minimal spiritual fulfillment, often feeling lost and disconnected.",
      2: "Slightly aware of spiritual needs, but struggling with purpose and inner peace.",
      3: "Occasionally feeling moments of spiritual connection, but they are fleeting and rare.",
      4: "Having some sense of spiritual awareness, but it is inconsistent and overshadowed by doubt.",
      5: "Moderately spiritually satisfied, experiencing occasional inner peace and purpose.",
      6: "Regularly feeling spiritually connected, with growing moments of inner peace and purpose.",
      7: "Often experiencing spiritual fulfillment, with a strong sense of purpose and frequent inner peace.",
      8: "Highly spiritually satisfied, with consistent inner peace and a clear sense of purpose.",
      9: "Experiencing profound spiritual fulfillment, with deep and sustained inner peace and purpose.",
      10: "Feeling spiritually fulfilled, experiencing deep inner peace and a strong sense of purpose."
    },
    'social connectivity': {
      0: "Completely isolated, lacking any meaningful social connections.",
      1: "Very lonely, minimal social connectivity and rare interactions.",
      2: "Disconnected, limited social interactions and frequent feelings of isolation.",
      3: "Somewhat isolated, occasional social engagements but still feeling disconnected.",
      4: "Slightly connected, some social interactions but not very strong or supportive.",
      5: "Moderately connected, a few meaningful relationships and occasional social interactions.",
      6: "Regularly engaged, growing network of social connections.",
      7: "Socially connected, several meaningful and supportive relationships.",
      8: "Highly connected, strong network of friends and supportive relationships.",
      9: "Profoundly connected, deep and meaningful social relationships.",
      10: "Highly socially connected, strong and supportive network of relationships."
    },
    'recognition': {
      0: "Completely unrecognized, lacking any acknowledgment or appreciation for your efforts.",
      1: "Minimally recognized, rarely feeling acknowledged for your contributions.",
      2: "Occasionally recognized, but infrequent and often feels insufficient.",
      3: "Sporadically recognized, some acknowledgment but not very meaningful.",
      4: "Occasionally acknowledged, but often feels superficial or lacking sincerity.",
      5: "Moderately recognized, with some acknowledgment for your efforts and contributions.",
      6: "Regularly recognized, with growing appreciation for your work.",
      7: "Often recognized, with frequent acknowledgment and appreciation for your contributions.",
      8: "Highly recognized, with consistent and meaningful acknowledgment for your efforts.",
      9: "Profoundly recognized, with deep appreciation and frequent acknowledgment for your contributions.",
      10: "Highly recognized, with frequent and significant acknowledgment for your efforts and contributions."
    },
    'sense of control': {
      0: "Completely powerless, lacking any influence over your circumstances.",
      1: "Very powerless, rarely able to influence or manage your life and environment.",
      2: "Slightly powerless, often feeling overwhelmed and unable to influence your circumstances.",
      3: "Occasionally in control, but influence is inconsistent and fleeting.",
      4: "Slightly influential, with moments of control but frequently feeling it is out of reach.",
      5: "Moderately in control, with some ability to manage and influence your life and environment.",
      6: "Regularly in control, with growing confidence in managing your circumstances.",
      7: "Often in control, with a strong ability to influence and manage your life and environment.",
      8: "Highly in control, consistently able to manage and influence your circumstances effectively.",
      9: "Profoundly in control, with deep confidence in your ability to influence and manage your life and environment.",
      10: "Highly in control, with a strong and consistent ability to influence and manage your life and environment."
    },
    'sense of superiority': {
      0: "No distinction, completely lacking any sense of being ahead of your peers.",
      1: "Very low sense of superiority, rarely feeling more capable or distinguished than others.",
      2: "Minimal sense of superiority, occasionally feeling slightly more capable than a few peers.",
      3: "Somewhat low sense of superiority, infrequently feeling ahead of some peers.",
      4: "Slight sense of superiority, occasionally feeling more capable than certain peers.",
      5: "Moderate sense of superiority, sometimes feeling more capable or distinguished than some peers.",
      6: "Noticeable sense of superiority, often feeling more capable or distinguished than many peers.",
      7: "Strong sense of superiority, frequently believing you are more capable or distinguished than most peers.",
      8: "Very strong sense of superiority, consistently feeling more capable or distinguished than nearly all peers.",
      9: "Extremely strong sense of superiority, feeling highly capable and distinguished over almost everyone.",
      10: "Complete sense of superiority, believing you are significantly more capable and distinguished than all those around you."
    },
    # 'sense of wonder': {
    #   0: "No curiosity or amazement about the world, lacking any interest in exploration or new experiences.",
    #   1: "Very low sense of wonder, rarely feeling curious or amazed by anything.",
    #   2: "Minimal sense of wonder, occasionally feeling a slight curiosity about the world.",
    #   3: "Somewhat low sense of wonder, infrequently feeling a mild interest in new experiences.",
    #   4: "Slight sense of wonder, occasionally feeling curious or amazed by certain things.",
    #   5: "Moderate sense of wonder, sometimes feeling curious and interested in exploring new things.",
    #   6: "Noticeable sense of wonder, often feeling curious and amazed by many aspects of the world.",
    #   7: "Strong sense of wonder, frequently feeling a deep fascination and desire to explore and understand the world.",
    #   8: "Very strong sense of wonder, consistently feeling captivated and eager to discover new things.",
    #   9: "Extremely strong sense of wonder, feeling intensely curious and amazed by almost everything around you.",
    #   10: "Complete sense of wonder, deeply fascinated and constantly seeking to discover, learn, and marvel at new things."
    # }
  }
